### ISSUE TITLE
Bug exemple V1

### ISSUE THREAD

**Issue by JulioJu** [AlexDmr/bshm#2]
Bonjour,

L'exemple V1 ne fonctionne pas chez moi. 

Au démarrage de node (`node mainV1.js`) j'ai l'erreur suivante : 

```
/home/(…)/Documents_Linux/DCISS/langageEtTechnoWeb2/AngularJs/bshm/Liste/V1/node_modules/angular/angular.js:31471
})(window);
   ^

ReferenceError: window is not defined
    at Object.<anonymous> (/home/(…)/Documents_Linux/DCISS/langageEtTechnoWeb2/AngularJs/bshm/Liste/V1/node_modules/angular/angular.js:31471:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/(…)/Documents_Linux/DCISS/langageEtTechnoWeb2/AngularJs/bshm/Liste/V1/node_modules/angular/index.js:1:63)
    at Module._compile (module.js:541:32)
```

Contrairement à V0, gulp compile sans problème. `npm install` renvoie les mêmes résultats que pour V0 et le projet amorcePAI, donc ce ne sembple pas être lui le coupable.

Je suis sous Arch Linux.

Comme pour V0, j'ai peut-être loupé quelque chose ?

Bien cordialement

Julio

**Comment by AlexDmr** [comment]
Les exemples fournis ne sont pas prévus pour s'exécuter dans un environnement NodeJS mais seulement dans un navigateur. 
Après avoir fait npm install pui gulp, il faut simplement ouvrir le ficheir index.html dans un navigateur (par glisser/déposer par exemple)

**Comment by JulioJu** [comment]
Merci !

Oui, il faut ouvrir le fichier liste.html. J'aurais dû m'en apercevoir si j'avais mieux regardé le code.

Julio
